// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ZHR6Xa78FUXHIIv7nFRSf-n9B5J0aTA',
    appId: '1:315156959888:web:b29180133a32aba599be15',
    messagingSenderId: '315156959888',
    projectId: 'listas-9b07b',
    authDomain: 'listas-9b07b.firebaseapp.com',
    storageBucket: 'listas-9b07b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Y28uw54hgJy2AswHrR_SbTwiO_h19fQ',
    appId: '1:315156959888:android:b3ca1c021b7239d699be15',
    messagingSenderId: '315156959888',
    projectId: 'listas-9b07b',
    storageBucket: 'listas-9b07b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1ZHR6Xa78FUXHIIv7nFRSf-n9B5J0aTA',
    appId: '1:315156959888:web:cef39b1c976dc30d99be15',
    messagingSenderId: '315156959888',
    projectId: 'listas-9b07b',
    authDomain: 'listas-9b07b.firebaseapp.com',
    storageBucket: 'listas-9b07b.firebasestorage.app',
  );
}
